language: java
jdk:
  - oraclejdk8

before_install:
  - git config --global push.default matching
  - git config --global user.name "aimer1124"
  - git config --global user.email "380774061@qq.com"
Script:
  - gradle clean gauge

branches:
  only:
  - master