language: java

jdk:
  - oraclejdk8

addons:
  chrome: stable


branches:
  only:
  - master
#
#cache:
#  directories:
#  - $HOME/.gradle

before_install:
  - git config --global push.default matching
  - git config --global user.name "aimer1124"
  - git config --global user.email "380774061@qq.com"
  - chmod a+x gradlew
  - brew install gauge
  - gauge install java

script:
  - ./gradlew -x assemble clean gauge
